/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page_kuhinja;
    QGraphicsView *graphicsView_kuhinja;
    QPushButton *pushButton_kuh_1;
    QLabel *label_kuh;
    QPushButton *pushButton_kuh_2;
    QPushButton *pushButton_fr;
    QPushButton *pushButton_pro;
    QWidget *page_kupatilo;
    QGraphicsView *graphicsView_kupatilo;
    QPushButton *pushButton_kup_1;
    QLabel *label_kup;
    QPushButton *pushButton_kup_2;
    QWidget *page_igraonica;
    QGraphicsView *graphicsView_igraonica;
    QPushButton *pushButton_igraon_1;
    QLabel *label_igraon;
    QPushButton *pushButton_igraon_2;
    QPushButton *pushButton_igra_1;
    QPushButton *pushButton_igra_2;
    QPushButton *pushButton_igra_3;
    QPushButton *pushButton_igra_4;
    QWidget *page_spavaca;
    QGraphicsView *graphicsView_spavaca;
    QPushButton *pushButton_spav_1;
    QLabel *label_spav;
    QPushButton *pushButton_spav_2;
    QWidget *page_prodavn;
    QGraphicsView *graphicsView_prodavn;
    QPushButton *pushButton_prod_nazad;
    QLabel *label_prodavn;
    QLabel *fj1_naziv_2;
    QPushButton *kupi_1;
    QLabel *vr_e_4;
    QPushButton *kupi_3;
    QPushButton *kupi_4;
    QLabel *fj4_naziv_2;
    QLabel *fj3_naziv_2;
    QLabel *pe1_vredn_1;
    QPushButton *kupi_2;
    QLabel *vr_e_1;
    QLabel *pe4_vredn_4;
    QLabel *vr_e_5;
    QPushButton *kupi_5;
    QLabel *pe2_vredn_2;
    QLabel *vr_e_2;
    QLabel *pe3_vredn_3;
    QLabel *vr_e_3;
    QLabel *pe5_vredn_5;
    QLabel *fj5_naziv_2;
    QLabel *fj2_naziv_2;
    QLabel *p5_cena_5;
    QLabel *p1_cena_1;
    QLabel *p2_cena_2;
    QLabel *p3_cena_3;
    QLabel *cena_2;
    QLabel *cena_3;
    QLabel *cena_4;
    QLabel *cena_5;
    QLabel *p4_cena_4;
    QLabel *cena_1;
    QWidget *page_friz;
    QGraphicsView *graphicsView_friz;
    QPushButton *pushButton_friz_nazad;
    QLabel *label_friz;
    QLabel *fj1_naziv;
    QLabel *fj2_naziv;
    QLabel *fj3_naziv;
    QLabel *fj4_naziv;
    QLabel *fj5_naziv;
    QLabel *fe1_vredn;
    QLabel *fe2_vredn;
    QLabel *fe3_vredn;
    QLabel *fe4_vredn;
    QLabel *fe5_vredn;
    QLabel *vr_1;
    QLabel *vr_2;
    QLabel *vr_3;
    QLabel *vr_4;
    QLabel *vr_5;
    QPushButton *jedi_1;
    QPushButton *jedi_2;
    QPushButton *jedi_3;
    QPushButton *jedi_4;
    QPushButton *jedi_5;
    QLabel *vr_kol_3;
    QLabel *vr_kol_1;
    QLabel *vr_kol_4;
    QLabel *kol_3;
    QLabel *vr_kol_5;
    QLabel *kol_2;
    QLabel *kol_4;
    QLabel *kol_1;
    QLabel *kol_5;
    QLabel *vr_kol_2;
    QWidget *page_igra_1;
    QPushButton *pushButton_igra_1_nazad;
    QWidget *page_igra_2;
    QPushButton *pushButton_igra_2_nazad;
    QWidget *page_igra_3;
    QPushButton *pushButton_igra_3_nazad;
    QWidget *page_igra_4;
    QPushButton *pushButton_igra_4_nazad;
    QProgressBar *SnagaBar;
    QLabel *label;
    QLabel *tajmer;
    QLabel *label_3;
    QLabel *ime;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(672, 471);
        MainWindow->setStyleSheet(QStringLiteral("background-color: rgb(0, 0, 0);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 50, 671, 391));
        stackedWidget->setStyleSheet(QStringLiteral(""));
        page_kuhinja = new QWidget();
        page_kuhinja->setObjectName(QStringLiteral("page_kuhinja"));
        page_kuhinja->setStyleSheet(QStringLiteral(""));
        graphicsView_kuhinja = new QGraphicsView(page_kuhinja);
        graphicsView_kuhinja->setObjectName(QStringLiteral("graphicsView_kuhinja"));
        graphicsView_kuhinja->setGeometry(QRect(10, -10, 681, 391));
        pushButton_kuh_1 = new QPushButton(page_kuhinja);
        pushButton_kuh_1->setObjectName(QStringLiteral("pushButton_kuh_1"));
        pushButton_kuh_1->setGeometry(QRect(141, 19, 80, 25));
        pushButton_kuh_1->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        label_kuh = new QLabel(page_kuhinja);
        label_kuh->setObjectName(QStringLiteral("label_kuh"));
        label_kuh->setGeometry(QRect(290, 20, 61, 17));
        label_kuh->setAutoFillBackground(false);
        label_kuh->setStyleSheet(QLatin1String("background-color: rgb(252, 175, 62);\n"
"font: 16pt \"Ubuntu\";"));
        label_kuh->setAlignment(Qt::AlignCenter);
        label_kuh->setWordWrap(true);
        label_kuh->setIndent(-1);
        pushButton_kuh_2 = new QPushButton(page_kuhinja);
        pushButton_kuh_2->setObjectName(QStringLiteral("pushButton_kuh_2"));
        pushButton_kuh_2->setGeometry(QRect(418, 19, 80, 25));
        pushButton_kuh_2->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        pushButton_fr = new QPushButton(page_kuhinja);
        pushButton_fr->setObjectName(QStringLiteral("pushButton_fr"));
        pushButton_fr->setGeometry(QRect(540, 40, 131, 271));
        pushButton_fr->setStyleSheet(QLatin1String("border-image: url(:/images/fridge_1.jpg);\n"
"\n"
"\n"
"\n"
""));
        pushButton_pro = new QPushButton(page_kuhinja);
        pushButton_pro->setObjectName(QStringLiteral("pushButton_pro"));
        pushButton_pro->setGeometry(QRect(30, 280, 81, 81));
        pushButton_pro->setStyleSheet(QStringLiteral("border-image: url(:/images/shop_1.jpg);"));
        stackedWidget->addWidget(page_kuhinja);
        page_kupatilo = new QWidget();
        page_kupatilo->setObjectName(QStringLiteral("page_kupatilo"));
        graphicsView_kupatilo = new QGraphicsView(page_kupatilo);
        graphicsView_kupatilo->setObjectName(QStringLiteral("graphicsView_kupatilo"));
        graphicsView_kupatilo->setGeometry(QRect(0, 0, 681, 391));
        pushButton_kup_1 = new QPushButton(page_kupatilo);
        pushButton_kup_1->setObjectName(QStringLiteral("pushButton_kup_1"));
        pushButton_kup_1->setGeometry(QRect(141, 21, 80, 25));
        pushButton_kup_1->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        label_kup = new QLabel(page_kupatilo);
        label_kup->setObjectName(QStringLiteral("label_kup"));
        label_kup->setGeometry(QRect(279, 21, 85, 17));
        label_kup->setStyleSheet(QLatin1String("background-color: rgb(233, 185, 110);\n"
"font: 16pt \"Ubuntu\";"));
        label_kup->setAlignment(Qt::AlignCenter);
        label_kup->setWordWrap(true);
        pushButton_kup_2 = new QPushButton(page_kupatilo);
        pushButton_kup_2->setObjectName(QStringLiteral("pushButton_kup_2"));
        pushButton_kup_2->setGeometry(QRect(418, 21, 80, 25));
        pushButton_kup_2->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_kupatilo);
        page_igraonica = new QWidget();
        page_igraonica->setObjectName(QStringLiteral("page_igraonica"));
        graphicsView_igraonica = new QGraphicsView(page_igraonica);
        graphicsView_igraonica->setObjectName(QStringLiteral("graphicsView_igraonica"));
        graphicsView_igraonica->setGeometry(QRect(0, 0, 681, 391));
        pushButton_igraon_1 = new QPushButton(page_igraonica);
        pushButton_igraon_1->setObjectName(QStringLiteral("pushButton_igraon_1"));
        pushButton_igraon_1->setGeometry(QRect(161, 21, 80, 25));
        pushButton_igraon_1->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        label_igraon = new QLabel(page_igraonica);
        label_igraon->setObjectName(QStringLiteral("label_igraon"));
        label_igraon->setGeometry(QRect(289, 21, 96, 17));
        QFont font;
        font.setFamily(QStringLiteral("Ubuntu"));
        font.setPointSize(16);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        label_igraon->setFont(font);
        label_igraon->setStyleSheet(QLatin1String("background-color: rgb(237, 212, 0);\n"
"font: 16pt \"Ubuntu\";"));
        label_igraon->setAlignment(Qt::AlignCenter);
        label_igraon->setWordWrap(true);
        pushButton_igraon_2 = new QPushButton(page_igraonica);
        pushButton_igraon_2->setObjectName(QStringLiteral("pushButton_igraon_2"));
        pushButton_igraon_2->setGeometry(QRect(418, 21, 80, 25));
        pushButton_igraon_2->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        pushButton_igra_1 = new QPushButton(page_igraonica);
        pushButton_igra_1->setObjectName(QStringLiteral("pushButton_igra_1"));
        pushButton_igra_1->setGeometry(QRect(20, 244, 61, 31));
        pushButton_igra_1->setStyleSheet(QStringLiteral("background-color: rgb(191, 64, 64);"));
        pushButton_igra_2 = new QPushButton(page_igraonica);
        pushButton_igra_2->setObjectName(QStringLiteral("pushButton_igra_2"));
        pushButton_igra_2->setGeometry(QRect(120, 220, 61, 31));
        pushButton_igra_2->setStyleSheet(QStringLiteral("background-color: rgb(115, 210, 22);"));
        pushButton_igra_3 = new QPushButton(page_igraonica);
        pushButton_igra_3->setObjectName(QStringLiteral("pushButton_igra_3"));
        pushButton_igra_3->setGeometry(QRect(490, 164, 61, 31));
        pushButton_igra_3->setStyleSheet(QStringLiteral("background-color: rgb(245, 121, 0);"));
        pushButton_igra_4 = new QPushButton(page_igraonica);
        pushButton_igra_4->setObjectName(QStringLiteral("pushButton_igra_4"));
        pushButton_igra_4->setGeometry(QRect(580, 190, 61, 31));
        pushButton_igra_4->setStyleSheet(QStringLiteral("background-color: rgb(173, 127, 168);"));
        stackedWidget->addWidget(page_igraonica);
        page_spavaca = new QWidget();
        page_spavaca->setObjectName(QStringLiteral("page_spavaca"));
        graphicsView_spavaca = new QGraphicsView(page_spavaca);
        graphicsView_spavaca->setObjectName(QStringLiteral("graphicsView_spavaca"));
        graphicsView_spavaca->setGeometry(QRect(0, 0, 681, 391));
        pushButton_spav_1 = new QPushButton(page_spavaca);
        pushButton_spav_1->setObjectName(QStringLiteral("pushButton_spav_1"));
        pushButton_spav_1->setGeometry(QRect(161, 21, 80, 25));
        pushButton_spav_1->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        label_spav = new QLabel(page_spavaca);
        label_spav->setObjectName(QStringLiteral("label_spav"));
        label_spav->setGeometry(QRect(276, 21, 98, 17));
        label_spav->setStyleSheet(QLatin1String("background-color: rgb(114, 159, 207);\n"
"font: 16pt \"Ubuntu\";\n"
""));
        label_spav->setAlignment(Qt::AlignCenter);
        label_spav->setWordWrap(true);
        pushButton_spav_2 = new QPushButton(page_spavaca);
        pushButton_spav_2->setObjectName(QStringLiteral("pushButton_spav_2"));
        pushButton_spav_2->setGeometry(QRect(391, 21, 80, 25));
        pushButton_spav_2->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_spavaca);
        page_prodavn = new QWidget();
        page_prodavn->setObjectName(QStringLiteral("page_prodavn"));
        graphicsView_prodavn = new QGraphicsView(page_prodavn);
        graphicsView_prodavn->setObjectName(QStringLiteral("graphicsView_prodavn"));
        graphicsView_prodavn->setGeometry(QRect(0, 1, 681, 391));
        graphicsView_prodavn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pushButton_prod_nazad = new QPushButton(page_prodavn);
        pushButton_prod_nazad->setObjectName(QStringLiteral("pushButton_prod_nazad"));
        pushButton_prod_nazad->setGeometry(QRect(50, 30, 89, 25));
        pushButton_prod_nazad->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        label_prodavn = new QLabel(page_prodavn);
        label_prodavn->setObjectName(QStringLiteral("label_prodavn"));
        label_prodavn->setGeometry(QRect(300, 40, 81, 17));
        label_prodavn->setStyleSheet(QLatin1String("background-color: rgb(252, 233, 79);\n"
"font: 15pt \"Ubuntu\";"));
        label_prodavn->setAlignment(Qt::AlignCenter);
        label_prodavn->setWordWrap(true);
        fj1_naziv_2 = new QLabel(page_prodavn);
        fj1_naziv_2->setObjectName(QStringLiteral("fj1_naziv_2"));
        fj1_naziv_2->setGeometry(QRect(10, 90, 67, 17));
        fj1_naziv_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj1_naziv_2->setWordWrap(true);
        kupi_1 = new QPushButton(page_prodavn);
        kupi_1->setObjectName(QStringLiteral("kupi_1"));
        kupi_1->setGeometry(QRect(570, 90, 89, 21));
        kupi_1->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        vr_e_4 = new QLabel(page_prodavn);
        vr_e_4->setObjectName(QStringLiteral("vr_e_4"));
        vr_e_4->setGeometry(QRect(280, 230, 51, 17));
        kupi_3 = new QPushButton(page_prodavn);
        kupi_3->setObjectName(QStringLiteral("kupi_3"));
        kupi_3->setGeometry(QRect(570, 180, 89, 21));
        kupi_3->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        kupi_4 = new QPushButton(page_prodavn);
        kupi_4->setObjectName(QStringLiteral("kupi_4"));
        kupi_4->setGeometry(QRect(570, 230, 89, 21));
        kupi_4->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        fj4_naziv_2 = new QLabel(page_prodavn);
        fj4_naziv_2->setObjectName(QStringLiteral("fj4_naziv_2"));
        fj4_naziv_2->setGeometry(QRect(10, 240, 67, 17));
        fj4_naziv_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj4_naziv_2->setWordWrap(true);
        fj3_naziv_2 = new QLabel(page_prodavn);
        fj3_naziv_2->setObjectName(QStringLiteral("fj3_naziv_2"));
        fj3_naziv_2->setGeometry(QRect(10, 190, 67, 17));
        fj3_naziv_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj3_naziv_2->setWordWrap(true);
        pe1_vredn_1 = new QLabel(page_prodavn);
        pe1_vredn_1->setObjectName(QStringLiteral("pe1_vredn_1"));
        pe1_vredn_1->setGeometry(QRect(190, 90, 71, 17));
        pe1_vredn_1->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pe1_vredn_1->setWordWrap(true);
        kupi_2 = new QPushButton(page_prodavn);
        kupi_2->setObjectName(QStringLiteral("kupi_2"));
        kupi_2->setGeometry(QRect(570, 130, 89, 21));
        kupi_2->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        vr_e_1 = new QLabel(page_prodavn);
        vr_e_1->setObjectName(QStringLiteral("vr_e_1"));
        vr_e_1->setGeometry(QRect(280, 90, 51, 17));
        vr_e_1->setStyleSheet(QStringLiteral(""));
        pe4_vredn_4 = new QLabel(page_prodavn);
        pe4_vredn_4->setObjectName(QStringLiteral("pe4_vredn_4"));
        pe4_vredn_4->setGeometry(QRect(190, 230, 71, 17));
        pe4_vredn_4->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pe4_vredn_4->setWordWrap(true);
        vr_e_5 = new QLabel(page_prodavn);
        vr_e_5->setObjectName(QStringLiteral("vr_e_5"));
        vr_e_5->setGeometry(QRect(280, 280, 51, 17));
        kupi_5 = new QPushButton(page_prodavn);
        kupi_5->setObjectName(QStringLiteral("kupi_5"));
        kupi_5->setGeometry(QRect(570, 280, 89, 21));
        kupi_5->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        pe2_vredn_2 = new QLabel(page_prodavn);
        pe2_vredn_2->setObjectName(QStringLiteral("pe2_vredn_2"));
        pe2_vredn_2->setGeometry(QRect(190, 130, 71, 17));
        pe2_vredn_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pe2_vredn_2->setWordWrap(true);
        vr_e_2 = new QLabel(page_prodavn);
        vr_e_2->setObjectName(QStringLiteral("vr_e_2"));
        vr_e_2->setGeometry(QRect(280, 130, 51, 17));
        pe3_vredn_3 = new QLabel(page_prodavn);
        pe3_vredn_3->setObjectName(QStringLiteral("pe3_vredn_3"));
        pe3_vredn_3->setGeometry(QRect(190, 180, 71, 17));
        pe3_vredn_3->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pe3_vredn_3->setWordWrap(true);
        vr_e_3 = new QLabel(page_prodavn);
        vr_e_3->setObjectName(QStringLiteral("vr_e_3"));
        vr_e_3->setGeometry(QRect(280, 180, 51, 17));
        pe5_vredn_5 = new QLabel(page_prodavn);
        pe5_vredn_5->setObjectName(QStringLiteral("pe5_vredn_5"));
        pe5_vredn_5->setGeometry(QRect(190, 280, 71, 17));
        pe5_vredn_5->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pe5_vredn_5->setWordWrap(true);
        fj5_naziv_2 = new QLabel(page_prodavn);
        fj5_naziv_2->setObjectName(QStringLiteral("fj5_naziv_2"));
        fj5_naziv_2->setGeometry(QRect(10, 290, 67, 17));
        fj5_naziv_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj5_naziv_2->setWordWrap(true);
        fj2_naziv_2 = new QLabel(page_prodavn);
        fj2_naziv_2->setObjectName(QStringLiteral("fj2_naziv_2"));
        fj2_naziv_2->setGeometry(QRect(10, 140, 67, 17));
        fj2_naziv_2->setStyleSheet(QLatin1String("background-color: rgb(233, 185, 110);\n"
""));
        fj2_naziv_2->setWordWrap(true);
        p5_cena_5 = new QLabel(page_prodavn);
        p5_cena_5->setObjectName(QStringLiteral("p5_cena_5"));
        p5_cena_5->setGeometry(QRect(370, 280, 71, 17));
        p5_cena_5->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        p5_cena_5->setWordWrap(true);
        p1_cena_1 = new QLabel(page_prodavn);
        p1_cena_1->setObjectName(QStringLiteral("p1_cena_1"));
        p1_cena_1->setGeometry(QRect(370, 90, 71, 17));
        p1_cena_1->setStyleSheet(QLatin1String("background-color: rgb(233, 185, 110);\n"
""));
        p1_cena_1->setWordWrap(true);
        p2_cena_2 = new QLabel(page_prodavn);
        p2_cena_2->setObjectName(QStringLiteral("p2_cena_2"));
        p2_cena_2->setGeometry(QRect(370, 130, 71, 17));
        p2_cena_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        p2_cena_2->setWordWrap(true);
        p3_cena_3 = new QLabel(page_prodavn);
        p3_cena_3->setObjectName(QStringLiteral("p3_cena_3"));
        p3_cena_3->setGeometry(QRect(370, 180, 71, 17));
        p3_cena_3->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        p3_cena_3->setWordWrap(true);
        cena_2 = new QLabel(page_prodavn);
        cena_2->setObjectName(QStringLiteral("cena_2"));
        cena_2->setGeometry(QRect(460, 130, 51, 17));
        cena_3 = new QLabel(page_prodavn);
        cena_3->setObjectName(QStringLiteral("cena_3"));
        cena_3->setGeometry(QRect(460, 180, 51, 17));
        cena_4 = new QLabel(page_prodavn);
        cena_4->setObjectName(QStringLiteral("cena_4"));
        cena_4->setGeometry(QRect(460, 230, 51, 17));
        cena_5 = new QLabel(page_prodavn);
        cena_5->setObjectName(QStringLiteral("cena_5"));
        cena_5->setGeometry(QRect(460, 280, 51, 17));
        p4_cena_4 = new QLabel(page_prodavn);
        p4_cena_4->setObjectName(QStringLiteral("p4_cena_4"));
        p4_cena_4->setGeometry(QRect(370, 230, 71, 17));
        p4_cena_4->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        p4_cena_4->setWordWrap(true);
        cena_1 = new QLabel(page_prodavn);
        cena_1->setObjectName(QStringLiteral("cena_1"));
        cena_1->setGeometry(QRect(460, 90, 51, 17));
        stackedWidget->addWidget(page_prodavn);
        graphicsView_prodavn->raise();
        cena_1->raise();
        fj1_naziv_2->raise();
        fj2_naziv_2->raise();
        fj4_naziv_2->raise();
        cena_2->raise();
        cena_3->raise();
        cena_4->raise();
        cena_5->raise();
        fj3_naziv_2->raise();
        fj5_naziv_2->raise();
        pe1_vredn_1->raise();
        p5_cena_5->raise();
        pe3_vredn_3->raise();
        kupi_2->raise();
        vr_e_3->raise();
        kupi_1->raise();
        p4_cena_4->raise();
        kupi_4->raise();
        pe2_vredn_2->raise();
        label_prodavn->raise();
        vr_e_1->raise();
        vr_e_4->raise();
        p3_cena_3->raise();
        pe5_vredn_5->raise();
        kupi_3->raise();
        p2_cena_2->raise();
        pushButton_prod_nazad->raise();
        vr_e_2->raise();
        vr_e_5->raise();
        p1_cena_1->raise();
        kupi_5->raise();
        pe4_vredn_4->raise();
        page_friz = new QWidget();
        page_friz->setObjectName(QStringLiteral("page_friz"));
        graphicsView_friz = new QGraphicsView(page_friz);
        graphicsView_friz->setObjectName(QStringLiteral("graphicsView_friz"));
        graphicsView_friz->setGeometry(QRect(0, 1, 681, 391));
        graphicsView_friz->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        pushButton_friz_nazad = new QPushButton(page_friz);
        pushButton_friz_nazad->setObjectName(QStringLiteral("pushButton_friz_nazad"));
        pushButton_friz_nazad->setGeometry(QRect(40, 20, 89, 25));
        pushButton_friz_nazad->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        label_friz = new QLabel(page_friz);
        label_friz->setObjectName(QStringLiteral("label_friz"));
        label_friz->setGeometry(QRect(300, 20, 51, 17));
        label_friz->setStyleSheet(QLatin1String("background-color: rgb(252, 233, 79);\n"
"font: 15pt \"Ubuntu\";"));
        label_friz->setAlignment(Qt::AlignCenter);
        label_friz->setWordWrap(true);
        fj1_naziv = new QLabel(page_friz);
        fj1_naziv->setObjectName(QStringLiteral("fj1_naziv"));
        fj1_naziv->setGeometry(QRect(20, 80, 67, 17));
        fj1_naziv->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj1_naziv->setWordWrap(true);
        fj2_naziv = new QLabel(page_friz);
        fj2_naziv->setObjectName(QStringLiteral("fj2_naziv"));
        fj2_naziv->setGeometry(QRect(20, 130, 67, 17));
        fj2_naziv->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj2_naziv->setWordWrap(true);
        fj3_naziv = new QLabel(page_friz);
        fj3_naziv->setObjectName(QStringLiteral("fj3_naziv"));
        fj3_naziv->setGeometry(QRect(20, 180, 67, 17));
        fj3_naziv->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj3_naziv->setWordWrap(true);
        fj4_naziv = new QLabel(page_friz);
        fj4_naziv->setObjectName(QStringLiteral("fj4_naziv"));
        fj4_naziv->setGeometry(QRect(20, 230, 67, 17));
        fj4_naziv->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj4_naziv->setWordWrap(true);
        fj5_naziv = new QLabel(page_friz);
        fj5_naziv->setObjectName(QStringLiteral("fj5_naziv"));
        fj5_naziv->setGeometry(QRect(20, 280, 67, 17));
        fj5_naziv->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fj5_naziv->setWordWrap(true);
        fe1_vredn = new QLabel(page_friz);
        fe1_vredn->setObjectName(QStringLiteral("fe1_vredn"));
        fe1_vredn->setGeometry(QRect(200, 80, 71, 17));
        fe1_vredn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fe1_vredn->setWordWrap(true);
        fe2_vredn = new QLabel(page_friz);
        fe2_vredn->setObjectName(QStringLiteral("fe2_vredn"));
        fe2_vredn->setGeometry(QRect(200, 130, 71, 17));
        fe2_vredn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fe2_vredn->setWordWrap(true);
        fe3_vredn = new QLabel(page_friz);
        fe3_vredn->setObjectName(QStringLiteral("fe3_vredn"));
        fe3_vredn->setGeometry(QRect(200, 180, 71, 17));
        fe3_vredn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fe3_vredn->setWordWrap(true);
        fe4_vredn = new QLabel(page_friz);
        fe4_vredn->setObjectName(QStringLiteral("fe4_vredn"));
        fe4_vredn->setGeometry(QRect(200, 230, 71, 17));
        fe4_vredn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fe4_vredn->setWordWrap(true);
        fe5_vredn = new QLabel(page_friz);
        fe5_vredn->setObjectName(QStringLiteral("fe5_vredn"));
        fe5_vredn->setGeometry(QRect(200, 280, 71, 17));
        fe5_vredn->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        fe5_vredn->setWordWrap(true);
        vr_1 = new QLabel(page_friz);
        vr_1->setObjectName(QStringLiteral("vr_1"));
        vr_1->setGeometry(QRect(310, 80, 51, 17));
        vr_2 = new QLabel(page_friz);
        vr_2->setObjectName(QStringLiteral("vr_2"));
        vr_2->setGeometry(QRect(310, 130, 51, 17));
        vr_3 = new QLabel(page_friz);
        vr_3->setObjectName(QStringLiteral("vr_3"));
        vr_3->setGeometry(QRect(310, 180, 51, 17));
        vr_4 = new QLabel(page_friz);
        vr_4->setObjectName(QStringLiteral("vr_4"));
        vr_4->setGeometry(QRect(310, 230, 51, 17));
        vr_5 = new QLabel(page_friz);
        vr_5->setObjectName(QStringLiteral("vr_5"));
        vr_5->setGeometry(QRect(310, 280, 51, 17));
        jedi_1 = new QPushButton(page_friz);
        jedi_1->setObjectName(QStringLiteral("jedi_1"));
        jedi_1->setGeometry(QRect(570, 80, 89, 21));
        jedi_1->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        jedi_2 = new QPushButton(page_friz);
        jedi_2->setObjectName(QStringLiteral("jedi_2"));
        jedi_2->setGeometry(QRect(570, 130, 89, 21));
        jedi_2->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        jedi_3 = new QPushButton(page_friz);
        jedi_3->setObjectName(QStringLiteral("jedi_3"));
        jedi_3->setGeometry(QRect(570, 180, 89, 21));
        jedi_3->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        jedi_4 = new QPushButton(page_friz);
        jedi_4->setObjectName(QStringLiteral("jedi_4"));
        jedi_4->setGeometry(QRect(570, 230, 89, 21));
        jedi_4->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        jedi_5 = new QPushButton(page_friz);
        jedi_5->setObjectName(QStringLiteral("jedi_5"));
        jedi_5->setGeometry(QRect(570, 280, 89, 21));
        jedi_5->setStyleSheet(QStringLiteral("background-color: rgb(186, 189, 182);"));
        vr_kol_3 = new QLabel(page_friz);
        vr_kol_3->setObjectName(QStringLiteral("vr_kol_3"));
        vr_kol_3->setGeometry(QRect(490, 180, 51, 17));
        vr_kol_1 = new QLabel(page_friz);
        vr_kol_1->setObjectName(QStringLiteral("vr_kol_1"));
        vr_kol_1->setGeometry(QRect(490, 80, 51, 17));
        vr_kol_4 = new QLabel(page_friz);
        vr_kol_4->setObjectName(QStringLiteral("vr_kol_4"));
        vr_kol_4->setGeometry(QRect(490, 230, 51, 17));
        kol_3 = new QLabel(page_friz);
        kol_3->setObjectName(QStringLiteral("kol_3"));
        kol_3->setGeometry(QRect(380, 180, 71, 17));
        kol_3->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        kol_3->setWordWrap(true);
        vr_kol_5 = new QLabel(page_friz);
        vr_kol_5->setObjectName(QStringLiteral("vr_kol_5"));
        vr_kol_5->setGeometry(QRect(490, 280, 51, 17));
        kol_2 = new QLabel(page_friz);
        kol_2->setObjectName(QStringLiteral("kol_2"));
        kol_2->setGeometry(QRect(380, 130, 71, 17));
        kol_2->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        kol_2->setWordWrap(true);
        kol_4 = new QLabel(page_friz);
        kol_4->setObjectName(QStringLiteral("kol_4"));
        kol_4->setGeometry(QRect(380, 230, 71, 17));
        kol_4->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        kol_4->setWordWrap(true);
        kol_1 = new QLabel(page_friz);
        kol_1->setObjectName(QStringLiteral("kol_1"));
        kol_1->setGeometry(QRect(380, 80, 71, 17));
        kol_1->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        kol_1->setWordWrap(true);
        kol_5 = new QLabel(page_friz);
        kol_5->setObjectName(QStringLiteral("kol_5"));
        kol_5->setGeometry(QRect(380, 280, 71, 17));
        kol_5->setStyleSheet(QStringLiteral("background-color: rgb(233, 185, 110);"));
        kol_5->setWordWrap(true);
        vr_kol_2 = new QLabel(page_friz);
        vr_kol_2->setObjectName(QStringLiteral("vr_kol_2"));
        vr_kol_2->setGeometry(QRect(490, 130, 51, 17));
        stackedWidget->addWidget(page_friz);
        page_igra_1 = new QWidget();
        page_igra_1->setObjectName(QStringLiteral("page_igra_1"));
        pushButton_igra_1_nazad = new QPushButton(page_igra_1);
        pushButton_igra_1_nazad->setObjectName(QStringLiteral("pushButton_igra_1_nazad"));
        pushButton_igra_1_nazad->setGeometry(QRect(50, 20, 89, 25));
        pushButton_igra_1_nazad->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_igra_1);
        page_igra_2 = new QWidget();
        page_igra_2->setObjectName(QStringLiteral("page_igra_2"));
        pushButton_igra_2_nazad = new QPushButton(page_igra_2);
        pushButton_igra_2_nazad->setObjectName(QStringLiteral("pushButton_igra_2_nazad"));
        pushButton_igra_2_nazad->setGeometry(QRect(50, 30, 89, 25));
        pushButton_igra_2_nazad->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_igra_2);
        page_igra_3 = new QWidget();
        page_igra_3->setObjectName(QStringLiteral("page_igra_3"));
        pushButton_igra_3_nazad = new QPushButton(page_igra_3);
        pushButton_igra_3_nazad->setObjectName(QStringLiteral("pushButton_igra_3_nazad"));
        pushButton_igra_3_nazad->setGeometry(QRect(40, 30, 89, 25));
        pushButton_igra_3_nazad->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_igra_3);
        page_igra_4 = new QWidget();
        page_igra_4->setObjectName(QStringLiteral("page_igra_4"));
        pushButton_igra_4_nazad = new QPushButton(page_igra_4);
        pushButton_igra_4_nazad->setObjectName(QStringLiteral("pushButton_igra_4_nazad"));
        pushButton_igra_4_nazad->setGeometry(QRect(50, 40, 89, 25));
        pushButton_igra_4_nazad->setStyleSheet(QStringLiteral("background-color: rgb(136, 138, 133);"));
        stackedWidget->addWidget(page_igra_4);
        SnagaBar = new QProgressBar(centralWidget);
        SnagaBar->setObjectName(QStringLiteral("SnagaBar"));
        SnagaBar->setGeometry(QRect(250, 20, 118, 23));
        SnagaBar->setStyleSheet(QStringLiteral(""));
        SnagaBar->setValue(24);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(290, 0, 67, 17));
        label->setStyleSheet(QStringLiteral(""));
        tajmer = new QLabel(centralWidget);
        tajmer->setObjectName(QStringLiteral("tajmer"));
        tajmer->setGeometry(QRect(170, 30, 67, 17));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(100, 30, 67, 17));
        ime = new QLabel(centralWidget);
        ime->setObjectName(QStringLiteral("ime"));
        ime->setGeometry(QRect(20, 10, 131, 17));
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        pushButton_kuh_1->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_kuh->setText(QApplication::translate("MainWindow", "Kuhinja", Q_NULLPTR));
        pushButton_kuh_2->setText(QApplication::translate("MainWindow", ">", Q_NULLPTR));
        pushButton_fr->setText(QString());
        pushButton_pro->setText(QString());
        pushButton_kup_1->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_kup->setText(QApplication::translate("MainWindow", "Kupatilo", Q_NULLPTR));
        pushButton_kup_2->setText(QApplication::translate("MainWindow", ">", Q_NULLPTR));
        pushButton_igraon_1->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_igraon->setText(QApplication::translate("MainWindow", "Igraonica", Q_NULLPTR));
        pushButton_igraon_2->setText(QApplication::translate("MainWindow", ">", Q_NULLPTR));
        pushButton_igra_1->setText(QApplication::translate("MainWindow", "Igra 1", Q_NULLPTR));
        pushButton_igra_2->setText(QApplication::translate("MainWindow", "Igra 2", Q_NULLPTR));
        pushButton_igra_3->setText(QApplication::translate("MainWindow", "Igra 3", Q_NULLPTR));
        pushButton_igra_4->setText(QApplication::translate("MainWindow", "Igra 4", Q_NULLPTR));
        pushButton_spav_1->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_spav->setText(QApplication::translate("MainWindow", "Spavaca soba", Q_NULLPTR));
        pushButton_spav_2->setText(QApplication::translate("MainWindow", ">", Q_NULLPTR));
        pushButton_prod_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_prodavn->setText(QApplication::translate("MainWindow", "Prodavnica", Q_NULLPTR));
        fj1_naziv_2->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        kupi_1->setText(QApplication::translate("MainWindow", "Kupi", Q_NULLPTR));
        vr_e_4->setText(QString());
        kupi_3->setText(QApplication::translate("MainWindow", "Kupi", Q_NULLPTR));
        kupi_4->setText(QApplication::translate("MainWindow", "Kupi", Q_NULLPTR));
        fj4_naziv_2->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj3_naziv_2->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        pe1_vredn_1->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        kupi_2->setText(QApplication::translate("MainWindow", "Kupi", Q_NULLPTR));
        vr_e_1->setText(QString());
        pe4_vredn_4->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        vr_e_5->setText(QString());
        kupi_5->setText(QApplication::translate("MainWindow", "Kupi", Q_NULLPTR));
        pe2_vredn_2->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        vr_e_2->setText(QString());
        pe3_vredn_3->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        vr_e_3->setText(QString());
        pe5_vredn_5->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        fj5_naziv_2->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj2_naziv_2->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        p5_cena_5->setText(QApplication::translate("MainWindow", "Cena", Q_NULLPTR));
        p1_cena_1->setText(QApplication::translate("MainWindow", "Cena", Q_NULLPTR));
        p2_cena_2->setText(QApplication::translate("MainWindow", "Cena", Q_NULLPTR));
        p3_cena_3->setText(QApplication::translate("MainWindow", "Cena", Q_NULLPTR));
        cena_2->setText(QString());
        cena_3->setText(QString());
        cena_4->setText(QString());
        cena_5->setText(QString());
        p4_cena_4->setText(QApplication::translate("MainWindow", "Cena", Q_NULLPTR));
        cena_1->setText(QString());
        pushButton_friz_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label_friz->setText(QApplication::translate("MainWindow", "Frizider", Q_NULLPTR));
        fj1_naziv->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj2_naziv->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj3_naziv->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj4_naziv->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fj5_naziv->setText(QApplication::translate("MainWindow", "Naziv", Q_NULLPTR));
        fe1_vredn->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        fe2_vredn->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        fe3_vredn->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        fe4_vredn->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        fe5_vredn->setText(QApplication::translate("MainWindow", "Energ. vr.", Q_NULLPTR));
        vr_1->setText(QString());
        vr_2->setText(QString());
        vr_3->setText(QString());
        vr_4->setText(QString());
        vr_5->setText(QString());
        jedi_1->setText(QApplication::translate("MainWindow", "Jedi", Q_NULLPTR));
        jedi_2->setText(QApplication::translate("MainWindow", "Jedi", Q_NULLPTR));
        jedi_3->setText(QApplication::translate("MainWindow", "Jedi", Q_NULLPTR));
        jedi_4->setText(QApplication::translate("MainWindow", "Jedi", Q_NULLPTR));
        jedi_5->setText(QApplication::translate("MainWindow", "Jedi", Q_NULLPTR));
        vr_kol_3->setText(QString());
        vr_kol_1->setText(QString());
        vr_kol_4->setText(QString());
        kol_3->setText(QApplication::translate("MainWindow", "Kolicina", Q_NULLPTR));
        vr_kol_5->setText(QString());
        kol_2->setText(QApplication::translate("MainWindow", "Kolicina", Q_NULLPTR));
        kol_4->setText(QApplication::translate("MainWindow", "Kolicina", Q_NULLPTR));
        kol_1->setText(QApplication::translate("MainWindow", "Kolicina", Q_NULLPTR));
        kol_5->setText(QApplication::translate("MainWindow", "Kolicina", Q_NULLPTR));
        vr_kol_2->setText(QString());
        pushButton_igra_1_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        pushButton_igra_2_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        pushButton_igra_3_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        pushButton_igra_4_nazad->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "SNAGA", Q_NULLPTR));
        tajmer->setText(QApplication::translate("MainWindow", "00:00", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Tajmer", Q_NULLPTR));
        ime->setText(QApplication::translate("MainWindow", "TextLabel", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
